apiVersion: skaffold/v4beta13
kind: Config

build:
  local:
    push: false

  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"

  artifacts:
    - image: ai-orchestration
      context: ai-orchestration
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "src/**"

    - image: agent
      context: sandbox/agent
      docker:
        dockerfile: dockerfile

    - image: router
      context: sandbox/router
      docker:
        dockerfile: dockerfile

    - image: sandbox
      context: sandbox/server
      docker:
        dockerfile: dockerfile

    - image: template
      context: sandbox/template
      docker:
        dockerfile: dockerfile

manifests:
  rawYaml:
    - k8s/*.yml

deploy:
  kubectl: {}