FROM node:20-bullseye

# Install build tools and Python 3 needed for node-pty
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN mkdir /workspace

CMD [ "npm", "run", "dev" ]